# Generated by Django 3.1.1 on 2021-03-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbCrypt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
