# Generated by Django 3.1.1 on 2021-03-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbCrypt', '0002_auto_20210313_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptuser',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cryptuser',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cryptuser',
            name='fullname',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cryptuser',
            name='key',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cryptuser',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cryptuser',
            name='phone',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cryptuser',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
