# Generated by Django 3.1.1 on 2021-03-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbCrypt', '0003_auto_20210313_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashedFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnameHashed', models.CharField(max_length=300)),
                ('usernameHashed', models.CharField(max_length=300)),
                ('passwordHashed', models.CharField(max_length=300)),
                ('emailHashed', models.CharField(max_length=300)),
                ('addressHashed', models.CharField(max_length=300)),
                ('phoneHashed', models.CharField(max_length=300)),
                ('keyHashed', models.CharField(max_length=300)),
            ],
        ),
    ]
